### ISSUE TITLE
login and register components make api calls

### ISSUE THREAD

**Issue by CleveyP** [EvanG13/Chess#24]
- [x] get the api gateway endpoints for login and register. 
- [x] put that base url in a .env 
- [x] install axios 
- [x] make axios calls to the endpoints using the .env file inside Register and Login components

**Comment by kysJune** [comment]
https://jqvrnfo1z4.execute-api.us-east-1.amazonaws.com/dev/login
https://jqvrnfo1z4.execute-api.us-east-1.amazonaws.com/dev/register

**Comment by CleveyP** [comment]
I closed this issue directly through the main branch. The .env issue was solved by installing react-native-dotenv as well as "metro-react-native-babel-preset".
